""" added normalize_type column

Revision ID: 0842241ea56a
Revises: 
Create Date: 2018-07-31 12:17:44.077119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0842241ea56a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datacatalog', sa.Column('normalize_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datacatalog', 'normalize_type')
    # ### end Alembic commands ###
